public Class merge2
{
public Account createAccount(String name)  //method to create account
{
//Add comment for Account A3
Account a3= new Account();
a3.Name = name;
return a3;
//this is the test comment
//test merge
//this is the in dev branch to test1 branch
//this is in dev to test1
//this is the in dev branch to test1 branch
//this is the test comment
//this is the in dev branch to test1 branch



}
}